/*
 * Employee API
 * Employees API using swagger.io by Tanmay Rajawat
 *
 * OpenAPI spec version: 1.0.0
 * Contact: tanmay.rajawat2019@vitbhopal.ac.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.Employee;
import io.swagger.client.model.Employees;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * 
     *
     * Operation to fetch all the employees
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void employeeGetTest() throws Exception {
        String employeename = null;
        Employees response = api.employeeGet(employeename);

        // TODO: test validations
    }
    /**
     * 
     *
     * Updates an existing employee
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void employeePutTest() throws Exception {
        Employee body = null;
        api.employeePut(body);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void employeefindGetTest() throws Exception {
        String find = null;
        Employees response = api.employeefindGet(find);

        // TODO: test validations
    }
    /**
     * 
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void employeeidDeleteTest() throws Exception {
        Integer id = null;
        Employee response = api.employeeidDelete(id);

        // TODO: test validations
    }
}
