/*
 * Employee API
 * Employees API using swagger.io by Tanmay Rajawat
 *
 * OpenAPI spec version: 1.0.0
 * Contact: tanmay.rajawat2019@vitbhopal.ac.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
