/*
 * Employee API
 * Employees API using swagger.io by Tanmay Rajawat
 *
 * OpenAPI spec version: 1.0.0
 * Contact: tanmay.rajawat2019@vitbhopal.ac.in
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * EmployeesInner
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-29T17:23:41.276563616Z[GMT]")
public class EmployeesInner {
  @SerializedName("EmployeeID")
  private Integer employeeID = null;

  @SerializedName("EmployeeName")
  private String employeeName = null;

  @SerializedName("Designation")
  private String designation = null;

  @SerializedName("Salary")
  private Integer salary = null;

  public EmployeesInner employeeID(Integer employeeID) {
    this.employeeID = employeeID;
    return this;
  }

   /**
   * Get employeeID
   * @return employeeID
  **/
  @Schema(example = "3", description = "")
  public Integer getEmployeeID() {
    return employeeID;
  }

  public void setEmployeeID(Integer employeeID) {
    this.employeeID = employeeID;
  }

  public EmployeesInner employeeName(String employeeName) {
    this.employeeName = employeeName;
    return this;
  }

   /**
   * Get employeeName
   * @return employeeName
  **/
  @Schema(example = "Sam", description = "")
  public String getEmployeeName() {
    return employeeName;
  }

  public void setEmployeeName(String employeeName) {
    this.employeeName = employeeName;
  }

  public EmployeesInner designation(String designation) {
    this.designation = designation;
    return this;
  }

   /**
   * Get designation
   * @return designation
  **/
  @Schema(example = "Software Developer", description = "")
  public String getDesignation() {
    return designation;
  }

  public void setDesignation(String designation) {
    this.designation = designation;
  }

  public EmployeesInner salary(Integer salary) {
    this.salary = salary;
    return this;
  }

   /**
   * Get salary
   * @return salary
  **/
  @Schema(example = "50000", description = "")
  public Integer getSalary() {
    return salary;
  }

  public void setSalary(Integer salary) {
    this.salary = salary;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EmployeesInner employeesInner = (EmployeesInner) o;
    return Objects.equals(this.employeeID, employeesInner.employeeID) &&
        Objects.equals(this.employeeName, employeesInner.employeeName) &&
        Objects.equals(this.designation, employeesInner.designation) &&
        Objects.equals(this.salary, employeesInner.salary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(employeeID, employeeName, designation, salary);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EmployeesInner {\n");
    
    sb.append("    employeeID: ").append(toIndentedString(employeeID)).append("\n");
    sb.append("    employeeName: ").append(toIndentedString(employeeName)).append("\n");
    sb.append("    designation: ").append(toIndentedString(designation)).append("\n");
    sb.append("    salary: ").append(toIndentedString(salary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
